'use strict';
const $=id=>document.getElementById(id),names={B:'Real-ESRGAN',H:'HAT',S:'Swin2SR',A:'SwinIR',F:'codeFormer',G:'GFPGAN'};
const upscaleModels=['B','S','H'];
const descriptions={
 B:'Model untuk memperjelas foto buram, gambar anime, dan gambar dari media sosial dengan hasil yang tajam.',
 S:'Pengembangan SwinIR untuk meningkatkan resolusi dan mengurangi artefak kompresi, seperti blok atau pola pecah pada gambar.',
 H:'Model berbasis Transformer dengan mekanisme perhatian hibrida untuk meningkatkan resolusi, ketajaman tekstur, dan kerapian garis.'};
let token='',photo=null,regions=[],history=[],tool='brush',drawing=false,startPoint=null,lastPoint=null,polygon=[],presets=[],job=null,busy=false,zoom=0,displayItems=[],resultSize=null;
let gallery=[],selected=-1,ready={},preferredDevice='cuda',batchState=null,resultJob=null;
const ctx=$('mask').getContext('2d');
function message(text,tone='notice',showResults=false){$('message-text').textContent=text;$('message').hidden=!text;$('message').classList.toggle('success',tone==='success');$('view-completed').hidden=!showResults}
$('message-close').onclick=()=>message('');
async function api(path,data,raw=false){const opts=data===undefined?{}:{method:'POST',headers:{'X-Studio-Token':token,...(raw?{'X-Filename':encodeURIComponent(data.name)}:{'Content-Type':'application/json'})},body:raw?data:JSON.stringify(data)};const response=await fetch(path,opts);const body=await response.json();if(!response.ok)throw Error(body.error||'Permintaan gagal.');return body}
function option(value,text){const o=document.createElement('option');o.value=value;o.textContent=text;return o}
function renderPresets(){const old=$('presets').value;$('presets').replaceChildren(option('','Pilih preset…'),option('builtin-photo','Real-ESRGAN + Swin2SR · Foto/Keluarga'),option('builtin-poster','Real-ESRGAN + Swin2SR · Poster'),...presets.map(p=>option(p.id,p.name)));if(presets.some(p=>p.id===old))$('presets').value=old}
function defaults(mode){const single=mode.startsWith('single'),m=upscaleModels.includes(mode.split('-')[1])?mode.split('-')[1]:'B';const weights=Object.fromEntries(upscaleModels.map(k=>[k,0]));if(single)weights[m]=100;else{weights.S=mode==='c-poster'?0:65;weights.B=mode==='c-poster'?100:35}return {output_scale:4,weights,reference:'S',tile:128,overlap:32,b_tile:256,h_tile:64,denoise:.5,feather:mode==='c-poster'?5:10,device:preferredDevice,use_mask:!single,face_model:''}}
// Keep old presets/history editable without reactivating face restoration.
function upscaleConfig(raw){
 const c={...raw,weights:Object.fromEntries(upscaleModels.map(m=>[m,raw.weights?.[m]||0])),face_model:''};
 c.weights.S+=(raw.weights?.A||0);
 const largest=Math.max(...Object.values(c.weights));if(largest>100)for(const m of upscaleModels)c.weights[m]=100*c.weights[m]/largest;
 delete c.fidelity;delete c.face_mix;
 if(!Object.values(c.weights).some(v=>v>0)){c.weights.B=100;c.use_mask=false;c.output_scale=4}
 if(!upscaleModels.includes(c.reference))c.reference='S';
 c.label=configName(c);return c;
}
function configName(c){const parts=upscaleModels.filter(m=>c.weights[m]>0).map(m=>names[m]);if(c.use_mask&&parts.length===1&&c.reference&&!parts.includes(names[c.reference]))parts.unshift(names[c.reference]);return parts.join(' + ')}
function configure(c,prefix=''){c=upscaleConfig(c);const $=id=>document.getElementById(prefix+id);for(const [id,value]of Object.entries({'output-scale':c.output_scale??2,wb:c.weights.B||0,ws:c.weights.S||0,wh:c.weights.H||0,reference:c.reference,tile:c.tile,overlap:c.overlap,'b-tile':c.b_tile,'h-tile':c.h_tile||64,denoise:c.denoise,feather:c.feather,device:c.device}))$(id).value=value;updateLabels(prefix)}
function readConfig(prefix=''){const $=id=>document.getElementById(prefix+id);const c={...defaults('custom'),weights:{B:+$('wb').value,S:+$('ws').value,H:+$('wh').value},output_scale:+$('output-scale').value,reference:$('reference').value,tile:+$('tile').value,overlap:+$('overlap').value,b_tile:+$('b-tile').value,h_tile:+$('h-tile').value,denoise:+$('denoise').value,feather:+$('feather').value,device:$('device').value,face_model:''};if($('mode').value==='single'){c.weights=defaults('single-'+$('single-model').value).weights;c.use_mask=false}c.output_scale=scaleAllowed(c)?c.output_scale:2;c.label=configName(c);return c}
function allConfigs(){const result=[readConfig()];if($('compare').checked)result.push(readConfig('second-'));return result}
function loadEditor(c,prefix=''){c=upscaleConfig(c);if(preferredDevice==='cpu'&&$('device').querySelector('[value="cuda"]').disabled)c={...c,device:'cpu'};const get=id=>$(prefix+id);const active=Object.keys(c.weights).filter(m=>c.weights[m]>0);get('mode').value=c.use_mask||active.length>1?'custom':'single';get('single-model').value=active[0]||'B';configure(c,prefix);modeUI(prefix)}
function loadConfigs(configs){loadEditor(configs[0]);$('compare').checked=configs.length===2;if(configs[1])loadEditor(configs[1],'second-');compareUI()}
function presetVisibility(){const custom=$('mode').value==='custom'||($('compare').checked&&$('second-mode')?.value==='custom');$('preset-row').hidden=!custom}
function compareUI(){presetVisibility();$('compare-options').hidden=!$('compare').checked;$('config-a-title').hidden=!$('compare').checked;updateProcess();syncMaskTools()}
function updateProcess(){const configs=allConfigs();$('process').disabled=busy||($('batch-mode').checked?!gallery.length:!photo)||configs.some(c=>!Object.values(c.weights).some(v=>v>0))}
function syncMaskTools(){document.querySelector('.photo-panel').classList.toggle('single-view',!allConfigs().some(c=>c.use_mask))}
function modeUI(prefix=''){presetVisibility();const $=id=>document.getElementById(prefix+id);const single=$('mode').value==='single',custom=$('mode').value==='custom';$('single-field').hidden=!single;$('weights').hidden=single;$('ws-row').hidden=!custom;$('wh-row').hidden=!custom;$('ref-field').hidden=single;$('reference').disabled=!custom;if(document.getElementById('second-mode'))syncMaskTools();$('mode-note').textContent=single?'Pilih model untuk meningkatkan resolusi foto.':'Model diproses bergantian. Hasil digabungkan setelah pemrosesan selesai.';updateSettings(prefix)}
function scaleAllowed(c){const active=Object.keys(c.weights).filter(m=>c.weights[m]>0);return active.length>0&&active.every(m=>['B','H','S'].includes(m))}
function updateSettings(prefix=''){const $=id=>document.getElementById(prefix+id);const c=readConfig(prefix),selectedModels=upscaleModels.filter(m=>c.weights[m]>0);const allowed=scaleAllowed(c),scale=$('output-scale');scale.querySelector('[value="4"]').disabled=!allowed;if(!allowed)scale.value='2';$('scale-field').hidden=$('mode').value==='single'&&!allowed;document.querySelector('.settings-panel .badge').textContent='KELUARAN '+readConfig().output_scale+'×';const set=new Set(selectedModels);document.getElementById(prefix?'config-secondary':'config-primary').querySelectorAll('[data-setting]').forEach(el=>{const kind=el.dataset.setting;el.hidden=kind==='mask'?!c.use_mask:kind==='AS'?!set.has('A')&&!set.has('S'):kind==='face'?!set.has('F')&&!set.has('G'):!set.has(kind)});$('model-description').replaceChildren();for(const m of selectedModels){const article=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=names[m];p.textContent=descriptions[m];article.append(h,p);if(ready[m]===false){const note=document.createElement('span');note.className='availability';note.textContent='Belum siap: bobot atau dependensi belum tersedia.';article.append(note)}$('model-description').append(article)}$('model-description').hidden=!selectedModels.length;$('selection-hint').hidden=Object.values(c.weights).some(v=>v>0);if(document.getElementById('second-mode'))updateProcess()}
function updateLabels(prefix=''){const $=id=>document.getElementById(prefix+id);const total=['wb','ws','wh'].reduce((s,id)=>s+ +$(id).value,0);for(const id of ['wb','ws','wh'])$(id+'-value').textContent=(total?100*+$(id).value/total:0).toFixed(0)+'%';$('denoise-value').textContent=(+$('denoise').value).toFixed(2);$('feather-value').textContent=$('feather').value+' px';for(const o of $('overlap').options)o.disabled=+o.value>=+$('tile').value;if(+$('overlap').value>=+$('tile').value)$('overlap').value='32';updateSettings(prefix)}
function resetMode(prefix=''){const $=id=>document.getElementById(prefix+id);configure(defaults($('mode').value==='single'?'single-'+$('single-model').value:$('mode').value),prefix);modeUI(prefix);updateLabels(prefix)}
const hrow=document.createElement('label');hrow.id='wh-row';hrow.innerHTML='HAT <output id="wh-value">0%</output><input id="wh" type="range" min="0" max="100" value="0" aria-label="Kontribusi HAT">';$('weights').append(hrow);
for(const id of ['wb','ws','wh'])$('weights').append($(id).closest('label'));
$('reference').replaceChildren(...upscaleModels.map(m=>option(m,names[m])));$('reference').value='S';
if(!$('reference').querySelector('[value="H"]'))$('reference').append(option('H','HAT'));
const secondary=$('config-primary').cloneNode(true);secondary.id='config-secondary';
for(const el of secondary.querySelectorAll('[id]'))el.id='second-'+el.id;
secondary.querySelector('h3').textContent='Konfigurasi B';secondary.querySelector('h3').hidden=false;
$('compare-options').append(secondary);
for(const prefix of ['', 'second-']){
 const get=id=>$(prefix+id);
 get('mode').onchange=()=>resetMode(prefix);get('single-model').onchange=()=>resetMode(prefix);get('reset').onclick=()=>resetMode(prefix);
 get('output-scale').onchange=()=>updateSettings(prefix);
 for(const id of ['wb','ws','wh','denoise','feather','tile','reference'])get(id).oninput=()=>{if(['wb','ws','wh','reference'].includes(id)){const allowed=scaleAllowed(readConfig(prefix));if(get('output-scale').querySelector('[value="4"]').disabled&&allowed)get('output-scale').value='4'}updateLabels(prefix)};
}
loadEditor(defaults('single-B'),'second-');
$('compare').onchange=compareUI;
$('view-completed').onclick=()=>{$('nav-studio').click();const target=batchState?.items?.length>1?$('batch-results'):$('results');target.hidden=false;target.scrollIntoView({behavior:'smooth'})};
$('save-preset').onclick=()=>{$('preset-dialog').showModal();$('preset-name').focus()};$('close-dialog').onclick=()=>$('preset-dialog').close();
$('preset-form').onsubmit=async e=>{e.preventDefault();try{presets=await api('/api/presets',{name:$('preset-name').value,configs:allConfigs()});renderPresets();$('preset-dialog').close();message('Preset parameter tersimpan; penandaan setiap foto tetap terpisah.','success')}catch(e){$('preset-dialog').close();message(e.message)}};
$('presets').onchange=()=>{if($('presets').value.startsWith('builtin-')){const kind=$('presets').value==='builtin-photo'?'c-photo':'c-poster';const c=defaults(kind);const known=photo?.known_config;if(known&&kind===(known.base_candidate_weight>.5?'c-poster':'c-photo')){c.weights.S=(1-known.base_candidate_weight)*100;c.weights.B=known.base_candidate_weight*100;c.feather=known.protected_regions[0]?.feather??c.feather;$('use-known').checked=true;drawMask()}loadConfigs([c]);return}const p=presets.find(p=>p.id===$('presets').value);if(p)loadConfigs(p.configs)};
$('delete-preset').onclick=async()=>{try{if(!$('presets').value)return;presets=await api('/api/presets/delete',{id:$('presets').value});renderPresets()}catch(e){message(e.message)}};
function remember(){if(selected<0||!gallery[selected])return;gallery[selected].regions=structuredClone(regions);gallery[selected].known=$('use-known').checked;gallery[selected].history=history;gallery[selected].configs=allConfigs();if(!$('editor').hidden)gallery[selected].custom=true}
function selectPhoto(index){if(busy)return;try{remember()}catch(e){message(e.message);return}selected=index;const item=gallery[index];photo=item.photo;regions=structuredClone(item.regions);history=item.history||[];polygon=[];$('photo').src=photo.original;$('mask').width=photo.size[0];$('mask').height=photo.size[1];$('filename').textContent=photo.name;$('dimensions').textContent=photo.size.join(' × ')+' px';$('known-line').hidden=!photo.known_config;$('use-known').checked=item.known;loadConfigs(item.configs);$('editor').hidden=false;$('input-grid').hidden=true;$('drop').hidden=true;$('back-grid').hidden=!$('batch-mode').checked;drawMask();updateProcess();photoHeader();$('results').hidden=true;if(item.result)renderResults(item.result)}
function photoHeader(){const multiple=$('batch-mode').checked,editing=!$('editor').hidden&&!!photo;
 $('back-grid').hidden=!multiple||!editing;$('apply-all').hidden=!multiple||!editing;
 $('replace-photo').hidden=multiple||!editing;$('remove-photo').hidden=!editing;
 $('photo-count').hidden=!multiple;$('photo-count').textContent=gallery.length+'/10';
 for(const id of ['back-grid','apply-all','replace-photo','remove-photo'])$(id).disabled=busy;
}
function card(item,index,result=false){const wrap=document.createElement('div');wrap.className='photo-card-wrap';const b=document.createElement('button');b.className='photo-card'+(index===selected?' active':'');b.disabled=busy&&!result;const img=document.createElement('img');img.src=result&&item.result?.results?.length?item.result.results[0].url:item.photo.original;img.alt=item.photo.name;const name=document.createElement('b');name.textContent=item.photo.name;const state=document.createElement('small');const statuses={waiting:'Menunggu',running:'Diproses',done:'Selesai',failed:'Gagal',cancelled:'Dibatalkan'};state.textContent=item.result?statuses[item.result.status]||'Siap':'Siap · '+item.photo.size.join(' × ');b.append(img,name,state);b.onclick=()=>{if(result){if(item.result?.status==='done')renderResults(item.result);else message(item.result?.error||state.textContent)}else selectPhoto(index)};wrap.append(b);
 if(!result){const remove=document.createElement('button');remove.className='remove-grid-photo';remove.textContent='×';remove.title='Hapus dari antrean';remove.setAttribute('aria-label','Hapus '+item.photo.name+' dari antrean');remove.disabled=busy;remove.onclick=()=>removePhoto(index);wrap.append(remove)}return wrap}
function emptyPhoto(){selected=-1;photo=null;regions=[];history=[];polygon=[];$('photo').removeAttribute('src');$('editor').hidden=true;$('results').hidden=true;$('drop').hidden=$('batch-mode').checked;}
function removePhoto(index){if(busy||!gallery[index])return;remember();const current=photo?.id;gallery.splice(index,1);selected=gallery.findIndex(i=>i.photo.id===current);if(selected<0)emptyPhoto();if($('batch-mode').checked){$('editor').hidden=true;$('input-grid').hidden=false;$('drop').hidden=true}grids();updateProcess();message('Foto dikeluarkan dari antrean. Berkas dan Riwayat tetap tersimpan.','success')}
function choosePhotos(){if(!busy){$('upload').value='';$('upload').click()}}
function addPhotoCard(){const b=document.createElement('button');b.className='add-photo-card';b.disabled=busy||gallery.length>=10;b.title='Klik atau seret foto ke sini';b.textContent=gallery.length>=10?'Batas 10 foto tercapai':'＋ Tambah foto';b.onclick=choosePhotos;return b}
function grids(){const multiple=$('batch-mode').checked;$('input-grid').replaceChildren(...gallery.map((item,i)=>card(item,i)),...(multiple?[addPhotoCard()]:[]));$('output-grid').replaceChildren(...gallery.filter(i=>i.result).map(item=>card(item,gallery.indexOf(item),true)));$('process').childNodes.forEach(n=>{if(n.nodeType===3)n.textContent=multiple?' Proses semua foto ':' Proses foto '});$('batch-results').hidden=!multiple||!gallery.some(i=>i.result);photoHeader()}
function showGrid(){remember();$('input-grid').hidden=false;$('editor').hidden=true;$('drop').hidden=true;grids()}
$('back-grid').onclick=showGrid;
$('replace-photo').onclick=choosePhotos;$('remove-photo').onclick=()=>removePhoto(selected);
$('batch-mode').onchange=()=>{if(busy)return;$('upload').multiple=$('batch-mode').checked;if($('batch-mode').checked)showGrid();else{$('input-grid').hidden=true;if(gallery.length)selectPhoto(Math.max(0,selected));else emptyPhoto();grids()}updateProcess()};
$('apply-all').onclick=()=>{try{remember();const configs=allConfigs();gallery.forEach(i=>{i.configs=structuredClone(configs);i.custom=false});message('Parameter diterapkan ke semua foto. Penandaan area tidak disalin.','success')}catch(e){message(e.message)}};
async function loadFiles(files){if(busy)return;files=Array.from(files);if(!files.length)return;const multiple=$('batch-mode').checked;if((multiple?gallery.length:0)+files.length>(multiple?10:1)){message(multiple?'Maksimal 10 foto. Kurangi jumlah pilihan.':'Aktifkan Multi-foto untuk memilih lebih dari satu.');return}
 let added=0,error=null;const replaceIndex=selected;
 try{remember();const configs=allConfigs();setBusy(true);for(const file of files){if(file.size>256*1024*1024)throw Error('Batas unggahan 256 MB per foto.');message('Memuat '+file.name+'…');const p=await api('/api/upload',file,true);const item={photo:p,regions:[],known:!!p.known_config,configs:structuredClone(configs),history:[]};if(!multiple&&replaceIndex>=0){gallery[replaceIndex]=item;selected=-1;photo=null}else gallery.push(item);added++}}
 catch(e){error=e.message}finally{setBusy(false);$('upload').value='';if(added){if(multiple)showGrid();else selectPhoto(replaceIndex>=0?replaceIndex:gallery.length-1);$('results').hidden=true}grids();updateProcess();message(error||'Foto siap. Pilih model dan proses saat setelan sudah sesuai.',error?'notice':'success')}
}
$('upload').onchange=e=>loadFiles(e.target.files);$('drop').onclick=choosePhotos;$('open-photo').onclick=e=>{e.stopPropagation();choosePhotos()};$('drop').onkeydown=e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();choosePhotos()}};
for(const target of [$('drop'),$('input-grid')]){for(const event of ['dragenter','dragover'])target.addEventListener(event,e=>{e.preventDefault();if(!busy)target.classList.add('drag')});target.ondragleave=()=>target.classList.remove('drag');target.ondrop=e=>{e.preventDefault();target.classList.remove('drag');loadFiles(e.dataTransfer.files)}}
function setBusy(value){busy=value;$('controls').disabled=value;$('upload').disabled=value;updateProcess();$('use-known').disabled=value;$('batch-mode').disabled=value;document.querySelectorAll('.toolbar button,.toolbar input').forEach(b=>b.disabled=value);grids()}
$('process').onclick=async()=>{try{message('');remember();if(polygon.length)throw Error('Selesaikan poligon dengan klik dua kali.');const chosen=$('batch-mode').checked?gallery:[gallery[selected]];const items=chosen.map(i=>({upload:i.photo.id,configs:($('editor').hidden&&!i.custom?allConfigs():i.configs).map(upscaleConfig),regions:i.regions,use_known:i.known}));if(!items.length)throw Error('Pilih foto terlebih dahulu.');setBusy(true);const data=await api('/api/jobs',{items});job=data.id;sessionStorage.setItem('ronaJob',job);$('progress-panel').hidden=false;$('cancel').disabled=false;poll()}catch(e){setBusy(false);message(e.message)}};
$('cancel').onclick=async()=>{try{await api('/api/cancel',{id:job});$('cancel').disabled=true;$('stage').textContent='Membatalkan setelah tahap yang sedang berjalan…'}catch(e){message(e.message)}};
async function poll(){try{const data=await api('/api/jobs/'+job);batchState=data;const running=data.items?.find(i=>i.status==='running');$('stage').textContent=data.stage+(running?' · '+running.stage:'');const percent=Math.max(0,Math.min(100,data.percent));$('percent').textContent=percent+'%';$('progress').setAttribute('aria-valuenow',percent);$('progress-fill').style.width=percent+'%';$('current-progress').textContent=running?'Foto '+(data.items.indexOf(running)+1)+' dari '+data.items.length+' · Progres foto: '+running.percent+'%':'';for(const child of data.items||[]){const item=gallery.find(i=>i.photo.id===child.upload);if(item)item.result=child}grids();if(data.status==='running'){setTimeout(poll,800);return}setBusy(false);$('progress-panel').hidden=true;sessionStorage.removeItem('ronaJob');if(data.items?.length===1&&data.items[0].status==='done')renderResults(data.items[0]);else{$('batch-results').hidden=false;$('results').hidden=true;$('batch-results').scrollIntoView({behavior:'smooth'})}const failed=data.items?.filter(i=>i.status==='failed')||[];const done=data.items?.filter(i=>i.status==='done').length||0;const summary=data.items?.length===1&&done?'Gambar selesai diproses.':done+' gambar selesai'+(failed.length?', '+failed.length+' gagal':'')+(data.status==='cancelled'?' · Antrean dibatalkan.':'.');message(summary,!failed.length&&data.status!=='cancelled'?'success':'notice',done>0);}catch(e){setBusy(false);message(e.message)}}
function renderResults(data){resultJob=data.id;displayItems=[{label:'Asli · tampilan disesuaikan',url:'/files/'+data.upload+'/original.png'},...data.results.map(r=>({...r,label:r.label+(r.output_scale?' · '+r.output_scale+'×':'')}))];resultSize=data.results[0].size;for(const side of ['left','right'])$(side).replaceChildren(...displayItems.map((r,i)=>option(String(i),r.label)));$('left').value=data.results.length===2?'1':'0';$('right').value=String(data.results.length);$('result-info').textContent=data.seconds.toFixed(1)+' detik · '+data.results.length+' hasil · '+data.reused+'/'+data.model_runs+' hasil model digunakan kembali';$('downloads').replaceChildren();for(const [index,result]of data.results.entries()){const a=document.createElement('a');a.href=result.url;a.download='rona-hasil-'+(index+1)+'.png';a.textContent='Unduh '+result.label;$('downloads').append(a)}const link=$('parameter-download');link.href=data.manifest;link.download='processing.json';$('results').hidden=false;$('back-results').hidden=!(batchState?.items?.length>1);zoom=0;showResult();$('results').scrollIntoView({behavior:'smooth',block:'start'})}
$('back-results').onclick=()=>{$('results').hidden=true;$('batch-results').hidden=false;$('batch-results').scrollIntoView({behavior:'smooth'})};
function setZoom(){if(resultSize)$('result-stage').style.width=zoom?Math.round(resultSize[0]*zoom)+'px':'100%'}
function showResult(){const right=displayItems[+$('right').value],left=displayItems[+$('left').value];resultSize=(right.size||left.size||resultSize);for(const [side,img]of [['left','result-top'],['right','result-base']]){const item=displayItems[+$(side).value];$(img).src=item.url;$(side+'-label').textContent=item.label}$('result-stage').style.aspectRatio=resultSize[0]+'/'+resultSize[1];$('result-base').style.height='100%';setZoom();wipe()}
function wipe(){const v=+$('wipe').value;$('result-over').style.clipPath='inset(0 '+(100-v)+'% 0 0)';$('divider').style.left=v+'%'}
$('left').onchange=showResult;$('right').onchange=showResult;$('wipe').oninput=wipe;$('fit').onclick=()=>{zoom=0;setZoom()};$('native').onclick=()=>{zoom=1;setZoom()};$('zoom-in').onclick=()=>{zoom=Math.min(4,(zoom||$('result-viewport').clientWidth/resultSize[0])*1.25);setZoom()};$('zoom-out').onclick=()=>{zoom=Math.max(.1,(zoom||$('result-viewport').clientWidth/resultSize[0])/1.25);setZoom()};
let pan=null;$('result-viewport').onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();pan={x:e.clientX,y:e.clientY,l:$('result-viewport').scrollLeft,t:$('result-viewport').scrollTop};$('result-viewport').setPointerCapture(e.pointerId)};$('result-viewport').onpointermove=e=>{if(!pan)return;$('result-viewport').scrollLeft=pan.l+pan.x-e.clientX;$('result-viewport').scrollTop=pan.t+pan.y-e.clientY};$('result-viewport').onpointerup=()=>pan=null;$('result-viewport').onpointercancel=()=>pan=null;
$('folder').onclick=async()=>{try{await api('/api/open-folder',{id:resultJob})}catch(e){message(e.message)}};
(async()=>{try{const data=await api('/api/bootstrap');token=data.token;presets=data.presets;ready=data.models||{};if(data.device){preferredDevice=data.device.cuda?'cuda':'cpu';$('second-device').value=preferredDevice;if(!data.device.cuda){for(const id of ['device','second-device'])$(id).querySelector('[value="cuda"]').disabled=true;message('Mode CPU aktif. '+(data.device.reason||'GPU NVIDIA kompatibel tidak terdeteksi.'))}}renderPresets();$('mode').value='single';resetMode();if(data.active){job=data.active;setBusy(true);$('progress-panel').hidden=false;poll()}}catch(e){message(e.message)}})();

function point(e){const r=$('mask').getBoundingClientRect();return [Math.max(0,Math.min(photo.size[0],(e.clientX-r.left)*photo.size[0]/r.width)),Math.max(0,Math.min(photo.size[1],(e.clientY-r.top)*photo.size[1]/r.height))]}
function saveHistory(){history.push(structuredClone(regions));if(history.length>30)history.shift()}
function trace(points,fill=true){if(!points.length)return;ctx.beginPath();ctx.moveTo(...points[0]);for(const p of points.slice(1))ctx.lineTo(...p);if(fill){ctx.closePath();ctx.fill()}ctx.stroke()}
function regionPoints(r){if(r.polygon)return r.polygon;const [a,b,c,d]=r.box;return [[a,b],[c,b],[c,d],[a,d]]}
function drawMask(){ctx.clearRect(0,0,$('mask').width,$('mask').height);ctx.fillStyle='#eaa46655';ctx.strokeStyle='#bb713f';ctx.lineWidth=Math.max(1,photo?photo.size[0]/700:1);if(photo?.known_config&&$('use-known').checked)for(const r of photo.known_config.protected_regions)trace(regionPoints(r));for(const r of regions)trace(r.polygon);if(polygon.length)trace(polygon,false);const count=regions.length+(photo?.known_config&&$('use-known').checked?photo.known_config.protected_regions.length:0);$('mask-note').textContent=count?'Area jingga dipertahankan dari model perlindungan pada mode gabungan.':'Belum ada area terlindungi. Gabungan berlaku pada seluruh gambar.'}
function brush(p){const radius=+$('brush-size').value;if(regions.length>=4000)return;const points=Array.from({length:12},(_,i)=>[Math.max(0,Math.min(photo.size[0],p[0]+radius*Math.cos(i*Math.PI/6))),Math.max(0,Math.min(photo.size[1],p[1]+radius*Math.sin(i*Math.PI/6)))]);regions.push({polygon:points})}
function inside(p,points){let v=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])v=!v}return v}
for(const button of document.querySelectorAll('[data-tool]'))button.onclick=()=>{tool=button.dataset.tool;polygon=[];document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b===button));$('tool-hint').textContent=tool==='polygon'?'Klik titik batas. Klik dua kali untuk menyelesaikan poligon.':tool==='erase'?'Klik atau sapukan pada penandaan manual untuk menghapusnya. Untuk area bawaan gabungan, nonaktifkan penandaan terverifikasi.':tool==='rect'?'Tarik kotak pada area yang ingin dipertahankan.':'Sapukan kuas pada wajah, kain, logo, atau detail yang ingin dipertahankan.';drawMask()};
$('mask').onpointerdown=e=>{if(!photo||busy)return;e.preventDefault();const p=point(e);if(tool==='polygon'){polygon.push(p);drawMask();return}saveHistory();drawing=true;startPoint=p;lastPoint=p;$('mask').setPointerCapture(e.pointerId);if(tool==='brush')brush(p);if(tool==='erase')regions=regions.filter(r=>!inside(p,r.polygon));drawMask()};
$('mask').onpointermove=e=>{if(!drawing)return;const p=point(e);if(tool==='brush'){const distance=Math.hypot(p[0]-lastPoint[0],p[1]-lastPoint[1]);const steps=Math.max(1,Math.ceil(distance/(+$('brush-size').value/2)));for(let i=1;i<=steps;i++)brush([lastPoint[0]+(p[0]-lastPoint[0])*i/steps,lastPoint[1]+(p[1]-lastPoint[1])*i/steps]);lastPoint=p}else if(tool==='erase')regions=regions.filter(r=>!inside(p,r.polygon));drawMask();if(tool==='rect')trace([startPoint,[p[0],startPoint[1]],p,[startPoint[0],p[1]]])};
$('mask').onpointerup=e=>{if(!drawing)return;drawing=false;if(tool==='rect'){const p=point(e);if(Math.abs(p[0]-startPoint[0])>1&&Math.abs(p[1]-startPoint[1])>1)regions.push({polygon:[startPoint,[p[0],startPoint[1]],p,[startPoint[0],p[1]]]})}drawMask()};$('mask').onpointercancel=()=>{drawing=false;drawMask()};
$('mask').ondblclick=e=>{if(tool!=='polygon'||busy)return;e.preventDefault();if(polygon.length>=3){saveHistory();regions.push({polygon:polygon.slice(0,200)});polygon=[];drawMask()}};
$('undo').onclick=()=>{if(busy)return;if(polygon.length){polygon.pop()}else if(history.length)regions=history.pop();drawMask()};$('clear').onclick=()=>{if(busy)return;saveHistory();regions=[];polygon=[];drawMask()};$('use-known').onchange=drawMask;

// Reopen an existing upload rather than creating a new upload/cache directory.
function openHistoryEditor(data){
 if(busy)throw Error('Tunggu proses selesai sebelum mengedit riwayat.');
 const item={photo:data.photo,regions:data.regions||[],known:!!data.known,configs:data.configs,history:[],custom:true};
 gallery=[item];selected=-1;photo=null;regions=[];history=[];polygon=[];batchState=null;resultJob=null;
 $('batch-mode').checked=false;$('upload').multiple=false;message('');
 $('batch-results').hidden=true;$('results').hidden=true;selectPhoto(0);grids();
 message('Foto dari riwayat siap diedit. Ganti metode atau parameter, lalu tekan Proses foto. Hasil lama tetap tersimpan.','success');
}
function forgetHistoryFiles(request){
 if(['all','upload'].includes(request.kind)){
  const current=photo?.id;gallery=gallery.filter(i=>request.kind!=='all'&&i.photo.id!==request.upload);
  selected=gallery.findIndex(i=>i.photo.id===current);
  if(selected<0){emptyPhoto();$('input-grid').hidden=!$('batch-mode').checked;}
 }
 if(['all','upload','run','result'].includes(request.kind)){
  for(const item of gallery)if(request.kind==='all'||item.photo.id===request.upload)item.result=null;
  $('results').hidden=true;$('batch-results').hidden=true;message('');
 }
 grids();updateProcess();
}
